### ISSUE TITLE
Using for other projects

### ISSUE THREAD

**Issue by iliakan** [reactjs/reactjs.org-translation#100]
Hello,

I maintain the Modern JavaScrtipt Tutorial at https://javascript.info, also translated to other languages. Thinking about using your automation tools :)

Is there any documentation for that? Maybe someone could help us to set it up?

**Comment by tesseralis** [comment]
Hi Ilya!

Unfortunately I don't have the time to make this a fully fledged library. If you'd like to use them, I'd recommend just cloning the repo and tweaking it to suit your needs. Feel free to ask me any questions about how the functions work!

**Comment by iliakan** [comment]
Thanks @tesseralis, the script for auto-syncing looks awesome, and the workflow seems convenient for our totally github-based translations ;)
