### ISSUE TITLE
Create subdomain for React documentation website in new languages

### ISSUE THREAD

**Issue by Bunlong** [reactjs/reactjs.org-translation#101]
Languages that don't have a subdomain yet:

* Greek (el)
* Gujarati (gu)
* Kurdish (ku)
* Central Khmer (km)
* Telugu (te)
* Lithuanian (lt)
* Urdu (ur)
* Swedish (sv)
* Thai (th)
* Georgian (ka)
* Kannada (kn)

**Comment by tesseralis** [comment]
@bvaughn could you take care of this and the other domains of languages that just started?

**Comment by bvaughn** [comment]
What "other domains" are you referring to?

**Comment by tesseralis** [comment]
Ones for languages that have started up after the last time you added the language subdomains

**Comment by bvaughn** [comment]
I don't know what those are. I'm not actively monitoring this effort.

**Comment by tesseralis** [comment]
Sure, I just assigned this issue to you and updated it with all the languages that don't have a subdomain yet.

**Comment by bvaughn** [comment]
The following Netlify and Cloudflare settings have been created:
- [x] Greek ([el.reactjs.org](https://el.reactjs.org))
- [x] Gujarati ([gu.reactjs.org](https://gu.reactjs.org))
- [x] Kurdish ([ku.reactjs.org](https://ku.reactjs.org))
- [x] Central Khmer ([km.reactjs.org](https://km.reactjs.org))
- [x] Telugu ([te.reactjs.org](https://te.reactjs.org))
- [x] Lithuanian ([lt.reactjs.org](https://lt.reactjs.org))
- [x] Urdu ([ur.reactjs.org](https://ur.reactjs.org))
- [x] Swedish ([sv.reactjs.org](https://sv.reactjs.org))
- [x] Thai ([th.reactjs.org](https://th.reactjs.org))
- [x] Georgian ([ka.reactjs.org](https://ka.reactjs.org))
- [x] Kannada ([kn.reactjs.org](https://kn.reactjs.org))

**Comment by Zorig** [comment]
@tesseralis how much translation needed to finish in order to get subdomain?

**Comment by Zorig** [comment]
@bvaughn @tesseralis said you will create a subdomain to get listed. Also, i tried to register in docsearch but it needs domain though.
