### ISSUE TITLE
Subdomains for new languages (Catalan and Hungarian)

### ISSUE THREAD

**Issue by tesseralis** [reactjs/reactjs.org-translation#118]
We need new subdomains for new translations of reactjs.org:

* [ ] Catalan (ca)
* [ ] Hungarian (hu)

**Comment by balazsorban44** [comment]
🎉🔥Tell me if we need to do anything special. I already set up Netlify for hosting.

**Comment by tesseralis** [comment]
@balazsorban44 don't worry! @bvaughn usually sets up the subdomains for all the languages :)

**Comment by balazsorban44** [comment]
Revisiting this, as the Hungarian `Core Pages` are nearly finished and according to https://github.com/reactjs/reactjs.org-translation#before-publishing, it is an indicator for soon getting a working domain. :)

**Comment by bvaughn** [comment]
I think I just setup hu.reactjs.org and ca.reactjs.org

**Comment by matyas-gubis** [comment]
Does anyone know anything about the current state of the Hungarian translations?
