### ISSUE TITLE
The bot stopped working?

### ISSUE THREAD

**Issue by smikitky** [reactjs/reactjs.org-translation#143]
Is the react translation bot up and running? We (ja.reactjs.org) did not receive auto-generated PRs on the last two Mondays (Apr 27 and May 4). Maybe the schedule has changed?

By the way, is there a way to check the log or manually invoke the sync process?

**Comment by tesseralis** [comment]
I think there just hasn't been any commits to the source in the past two weeks:

https://github.com/reactjs/reactjs.org/commits/master

Dan just committed a few hours ago, and before that the last commit was Apr 15.

**Comment by tesseralis** [comment]
Although if for whatever reason you want to trigger a manual sync you can do:

```shell
git remote add source https://github.com/reactjs/reactjs.org
git pull source master
```

And then fix the merge conflicts.

**Comment by smikitky** [comment]
Oh, I was under the impression that a PR will be created whenever there are unmerged commits, and our fork have ones since three weeks ago. Anyway, we'll wait until next Monday. Thanks.

**Comment by smikitky** [comment]
A PR was created as usual, sorry for this.
