### ISSUE TITLE
The website isreacttranslatedyet.com is not valid

### ISSUE THREAD

**Issue by jihoon-seo** [reactjs/reactjs.org-translation#164]
In [README.md](https://github.com/reactjs/reactjs.org-translation/blob/master/README.md#contributing-to-translations),
> Check www.isreacttranslatedyet.com to see if your language already has a translation effort in progress. Click on "Track Progress" on the language you want to contribute to in order to receive further instructions.

---

However,
- (https://www.isreacttranslatedyet.com , the `https` URL shows no webpage.)
- http://www.isreacttranslatedyet.com (the `http` URL)
![image](https://user-images.githubusercontent.com/46767780/111723796-7774ee80-88a7-11eb-9234-9547bd4b91a9.png)

**Comment by gaearon** [comment]
The site is currently broken but it's at https://translations.reactjs.org/.
