### ISSUE TITLE
www.isreacttranslatedyet.com  seems to be expired and claimed by someone else.

### ISSUE THREAD

**Issue by stultus** [reactjs/reactjs.org-translation#169]
[www.isreacttranslatedyet.com](www.isreacttranslatedyet.com)  seems to be expired and claimed by someone else.)  seems to be expired and claimed by someone else.

**Comment by bvaughn** [comment]
Good point. Looks like the domain expired and got picked up by squatters. That's unfortunate.

I've created a new subdomain:
translations.reactjs.org

And removed references to the old domain.
