### ISSUE TITLE
Why Brazilian Portuguese doesn't appear on translations page?

### ISSUE THREAD

**Issue by allankildare** [reactjs/reactjs.org-translation#175]
I've found the pt-BR json, but it doesn't appear on [ReactJS Translations page](https://translations.reactjs.org/).
It's possible find the Portuguese (Portugal), but not the Brazilian language.

<p align="center">
<img src="https://user-images.githubusercontent.com/50001206/139012043-1ebf8c63-7fc4-4193-9f9c-3a22b1900310.png" alt="">
<img src="https://user-images.githubusercontent.com/50001206/139011997-61c022ca-a36f-4011-bb58-b97c6ddd6d0f.png" alt="">
</p>
<p align="center">
<img src="https://user-images.githubusercontent.com/50001206/139011791-1b94fc03-4aac-4b5b-a65e-4c6123720bdb.png" width="200px">
</p>

**Comment by ottomicheletti** [comment]
I was also looking for that and to be able to be a part of the translation team. I'll keep an eye on this issue :eyes:

**Comment by arimariojesus** [comment]
I asked myself the same question!

I couldn't contain my curiosity and went to investigate, and then I found the problem. I uploaded a [correction](https://github.com/reactjs/is-react-translated-yet/pull/1), now just wait for an answer.

**Comment by gaearon** [comment]
Let's track in https://github.com/reactjs/reactjs.org-translation/issues/256.

**Comment by gaearon** [comment]
fixed
