### ISSUE TITLE
Korean is missing from https://translations.reactjs.org list.

### ISSUE THREAD

**Issue by thecode00** [reactjs/reactjs.org-translation#219]
There is a Korean translation: https://github.com/reactjs/ko.reactjs.org
but it is not list on the [translations.reactjs.org](https://translations.reactjs.org/) Please add it.

**Comment by gaearon** [comment]
Let's track in https://github.com/reactjs/reactjs.org-translation/issues/256.

**Comment by gaearon** [comment]
fixed
