### ISSUE TITLE
French accent is wrong

### ISSUE THREAD

**Issue by vjeux** [reactjs/reactjs.org-translation#38]
It is Franćais but should be Français

**Comment by vjeux** [comment]
![d469616c-dfb7-48db-b48f-933847ba5922](https://user-images.githubusercontent.com/197597/52675458-e1ff1780-2ef4-11e9-9f3b-ea018a2731f5.jpeg)

**Comment by tesseralis** [comment]
It's uh.

It's Quebecois.

(I just pushed a fix)

**Comment by vjeux** [comment]
Haha! Thanks for the quick fix!
