### ISSUE TITLE
Switch to Code Owners

### ISSUE THREAD

**Issue by tesseralis** [reactjs/reactjs.org-translation#50]
~~Assign each sync issue to (some subset of) the maintainers of the repo.

It's just kind of annoying to do it using GitHub's API.~~

The current system of managing managers for different translations is kind of annoying. We're using Github Teams for each language, which hasn't been the best.

* It doesn't automatically assign reviewers to PRs/issues
* It's impossible for people who are not members of the React organization to see who is in charge of a repo
* It requires us to manage private ~50 teams that people never actually use
* It requires us to maintain a separate inventory of maintainers in this repo that needs to be synced.

Code owners would fix these issues and hopefully more.

Open questions:

* What happens when someone who is not a member of an organization (but has an invitation) becomes a code owner? Need to make sure this works.

**Comment by tibuurcio** [comment]
Hey Nat, I don't quite understand the problem. How is the sync script doing it? And how it would do to assign maintainers without GitHub's API?

**Comment by halian-vilela** [comment]
> Hey Nat, I don't quite understand the problem. How is the sync script doing it? And how it would do to assign maintainers without GitHub's API (Do you mean GitHub's UI)?

Me neither, could you explain the issue a little bit further?

**Comment by tesseralis** [comment]
@tibuurcio @halian-vilela I just mean that when I create a [sync pull request](https://github.com/reactjs/pt-BR.reactjs.org/pull/128), I want to automatically assign "Reviewers" to you or the other pt-br maintainers. Since there are a lot of you, I want to do it in a way that makes sense. If I assign *all* of you then that might result in duplicated work. I was thinking of assigning the issue randomly to 2-3 maintainers.

**Comment by halian-vilela** [comment]
> @tibuurcio @halian-vilela I just mean that when I create a [sync pull request](https://github.com/reactjs/pt-BR.reactjs.org/pull/128), I want to automatically assign "Reviewers" to you or the other pt-br maintainers. Since there are a lot of you, I want to do it in a way that makes sense. If I assign _all_ of you then that might result in duplicated work. I was thinking of assigning the issue randomly to 2-3 maintainers.

Got it.. randomly to 2 maintainers seems reasonable to me.

**Comment by smikitky** [comment]
Randomly assigning two of the three maintainers may not make much sense at least in the Japanese fork. We check and approve each sync PR on a first-come basis. It should be either assigning everyone or assigning no one.

**Comment by QC-L** [comment]
At first, I thought so, but I found that not everyone could spare time. I also think we should assigning no one.

**Comment by smikitky** [comment]
If you want to always assign the same set of reviewers, I think you can just use the [code owners](https://github.blog/2017-07-06-introducing-code-owners/) functionality. Randomly picking a part of the reviewers is not possible, though.

**Comment by QC-L** [comment]
I also think we should assigning no one.

**Comment by tesseralis** [comment]
@QC-L could you elaborate on why?

**Comment by QC-L** [comment]
Random assignment does not necessarily mean someone will respond.
I refresh repo every day, so I will merge when I see it.
I assigned tasks to some people, but you may not receive mail.

**Comment by QC-L** [comment]
@tesseralis I agree to use [code owners](https://github.blog/2017-07-06-introducing-code-owners/).
