### ISSUE TITLE
Sync scripts: better pull request behavior

### ISSUE THREAD

**Issue by tesseralis** [reactjs/reactjs.org-translation#51]
Currently, if the sync script runs again before the previous one is merged, a duplicate PR is created (including new changes), and it's up to the maintainers to manually close the previous PR.

Honestly, I don't really know what's the best behavior in this situation. A few possibilities:

* Open a new PR and not do anything to the old one, and let the maintainers handle it (current behavior)
* Close out the previous PR (this means if someone has fixed the conflict before, they have to do it again)
* Just not open a new PR if the bot finds a current open sync PR.

What do people think?

**Comment by jakubdrozdek** [comment]
Is it possible to add commits to the old PR? That might help.

**Comment by asantarissy** [comment]
@tesseralis, is it possible to push new commits to the old PR, I know it's similar to option 2 (closing the previous PR) but I think it might be the best flow.

**Comment by tesseralis** [comment]
@jakubdrozdek @asantarissy I think that's probably the best option. It might be a little tricky since I need to make sure something like

<<<<<<HEAD
<<<<<<HEAD
const blah = "blah"
=======
=======
>>>>>> af28bc02
>>>>>> bc02391a

**Comment by asantarissy** [comment]
> @jakubdrozdek @asantarissy I think that's probably the best option. It might be a little tricky since I need to make sure it doesn't end up something like
> 
> ```
> <<<<<<HEAD
> <<<<<<HEAD
> const blah = "blah"
> =======
> =======
> >>>>>> af28bc02
> >>>>>> bc02391a
> ```

@tesseralis Yes true, but I think that we can manage 😅
