### ISSUE TITLE
Better way to credit contributors

### ISSUE THREAD

**Issue by tesseralis** [reactjs/reactjs.org-translation#74]
Currently, maintainers of a translation are listed in the `langs/` directory, but we don't have any way to credit *contributors* -- community members who provide translations but don't take care of the repo management.

Some ideas for this:

* Put it in the README or a CONTRIBUTORS page of the translation repo
* Add a "translators" property in the frontmatter of markdown docs, and show it on the page
  * I think this works for blog posts but not for other docs for the same reason people don't put authors on the docs in English. There's a lot of authors and the docs will change over a long period of time

Anyone have any ideas?

**Comment by tesseralis** [comment]
@gaearon what does the react team think of adding translator credits for pages?

**Comment by jakubdrozdek** [comment]
Glad you posted it, @tesseralis! :-) I think it's important to include those who help in any way. Some people are not good at Git stuff and don't necessarily want to be maintainers, yet are still really helpful with the translation process.
Sometimes, in computer games, contributors are mentioned in the "special thanks" section of credits. But translators should be treated almost equally as maintainers (who do translate, too). Still, some people help more, some add just one translation and stop. I think we could at least measure which translators contributed most and honor them somehow.

**Comment by QC-L** [comment]
We can provide a display for translation contributors by referring to a display page similar to [babel/team](https://babeljs.io/team) for contributors.

**Comment by rahulrana95** [comment]
@We can define credit points and can make a list sorted by desc and we can make a separate list for people who provide translations. and can even have a credit point for them and a separate table for them.  @tesseralis

**Comment by seven-deuce** [comment]
@tesseralis 
the crediting system for contributors will work, but i think we should find a way to reward them in a symbolic way. For example, React, T-shirts will be a great idea. we can define a minimum requirement, like translation of 3 pages and any translator who achieves that, will get a react t-shirt, or cap, or something similar.
What do you think?

**Comment by erdenezul** [comment]
Would love to have cool react t-shirts and stickers

**Comment by jakubdrozdek** [comment]
Yeah, it would be awesome to wear a T-shirt like that! Pride overflow :D

**Comment by OfficialMarinho** [comment]
It would be great if the organization had a bot that invite new collaborators who create merged PRs, just like @Gastby does.
